# Generated by Django 4.1.5 on 2023-01-09 10:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок поста')),
                ('text_news', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date', models.DateField(verbose_name='дата поста')),
                ('img', models.ImageField(upload_to='image_news/%Y', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
