# Generated by Django 4.1.5 on 2023-01-10 13:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='image_about/%Y', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': 'O нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
