# Generated by Django 4.1.5 on 2023-01-08 14:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок поста')),
                ('text_blog', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('author', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('date', models.DateField(verbose_name='дата поста')),
                ('img', models.ImageField(upload_to='image_blog/%Y', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
