# Generated by Django 4.1.5 on 2023-01-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_portfolio', '0002_alter_portfolio_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='img',
            field=models.ImageField(upload_to='images/portfolio', verbose_name='Изображения'),
        ),
    ]
