# Generated by Django 4.1.5 on 2023-01-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок поста')),
                ('price', models.CharField(max_length=20, verbose_name='цена')),
                ('text', models.TextField(verbose_name='Текст записи')),
                ('img', models.ImageField(upload_to='images/portfolio', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
